### ISSUE TITLE
Support building with GHC 9.10

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#2307]
Liquid Haskell builds with ghc 9.10 but the tests aren't passing yet.

[This](https://github.com/ucsd-progsys/liquidhaskell/compare/fd/ghc-9.10) is the branch with the work in progress.

**Comment by facundominguez** [comment]
@ranjitjhala, I'm having some difficulty debugging one of the test failures.

The following example passes verification with ghc-9.8 but fails with ghc-9.10.
```
module Wrap0 () where

-- Only fails with ghc 9.10 if the argument of flibInt is polymorphic.
{-@ flibInt :: a -> Bool @-}
flibInt x = prop1 x (x + 1)

prop1 x y = liquidAssertB (x < y)

{-@ liquidAssertB :: x:{v:Bool | v} -> {v: Bool | v} @-}
liquidAssertB :: Bool -> Bool
liquidAssertB x = x
```
Here's the error:
```
tests/pos/Wrap0.hs:9:27: error:
    Liquid Type Mismatch
    .
    The inferred type
      VV : {v : GHC.Types.Bool | (v <=> x##aVs < y##aVt)
                                 && v == (x##aVs < y##aVt)}
    .
    is not a subtype of the required type
      VV : {VV##428 : GHC.Types.Bool | VV##428}
    .
    in the context
      x##aVs : a
       
      y##aVt : a
    Constraint id 7
  |
9 | prop1 x y = liquidAssertB (x < y)
  |                           ^^^^^^^
```

There is a difference in the .fqout files. While ghc 9.10 produces
```
Solution:
$k_##235 := true
$k_##238 := true
```
ghc 9.8 says:
```
Solution:
$k_##284 := true
$k_##287 := $VV##286##k_ /= $x##aTT##k_
            && $VV##286##k_ > $x##aTT##k_
            && $VV##286##k_ >= $x##aTT##k_
```
The fixpoint query looks pretty much the same on both compilers
```
constraint:
  lhs {VV : bool | [(VV <=> (x < y)); (VV = (x < y))]}
  rhs {VV : bool | [VV]}
  id 7 tag [3]
  // META constraint id 7 : tests/pos/Wrap0.hs:7:27-33
  environment:
    // elided some likely irrelevant bindings
    
    x : {VV : a##aVO | [$k_##235]}
    y : {VV : a##aVO | [$k_##238]}
    _lq_anf$ : {lq_tmp$x : bool | [(lq_tmp$x <=> (x < y))]}
```
Any hints welcome.

Update: one of the other constraints talking about `$k_##235` is different. Perhaps that has something to do in a way that I cannot yet explain.
 
ghc 9.10:
```
constraint:
  lhs {VV : a | [(VV = (x + lq_anf$##d1XF))]}
  rhs {VV : a | [$k_##238[fix$36$$36$dOrd_aW0:=fix$36$$36$dOrd_aWB][VV##237:=VV][VV##F:=VV][lq_tmp$x##314:=VV][lq_tmp$x##319:=fix$36$$36$dOrd_aWB][lq_tmp$x##320:=x][lq_tmp$x##324:=VV][x##aVn:=x]]}
  id 2 tag [4]
  // META constraint id 2 : tests/pos/Wrap0.hs:5:21-27
  environment:
    // elided some likely irrelevant bindings
    
    $dOrd_aWB : {VV : (GHC.Classes.Ord a) | []}
    
    a : {VV : num | []}
    
    lq_anf$##d1XF :
      {lq_tmp$x : int |
         [((lqdc##$select##GHC.Num.Integer.IS##1 lq_tmp$x) = 1)]}
    
    x : {VV : a | []}
    
    _lq_anf$##d1XG : {lq_tmp$x : a | [(lq_tmp$x = lq_anf$##d1XF)]}
    
    _lq_anf$##d1XH :
      {lq_tmp$x : a | [(lq_tmp$x = (x + lq_anf$##d1XF))]}
```
vs ghc 9.8
```
constraint:
  lhs {VV : a | [(VV = (x + (coerce int ~ a in (1  :  int))))]}
  rhs {VV : a | [$k_##287[fix$36$$36$dOrd_aUv:=fix$36$$36$dOrd_aV5][VV##286:=VV][VV##F:=VV][lq_tmp$x##363:=VV][lq_tmp$x##368:=fix$36$$36$dOrd_aV5][lq_tmp$x##369:=x][lq_tmp$x##373:=VV][x##aTT:=x]]}
  id 2 tag [3]
  // META constraint id 2 : ../liquidhaskell/tests/pos/Wrap0.hs:5:21-27
  environment:
    // elided some likely irrelevant bindings
    
    $dOrd_aV5 : {VV : (GHC.Classes.Ord a) | []}
    
    a : {VV : num | []}
    
    x : {VV : a | []}
    
    _lq_anf$ :
      {lq_tmp$x : a |
         [(lq_tmp$x = (x + (coerce int ~ a in (1  :  int))))]}
```

**Comment by ranjitjhala** [comment]
Hmm have you tried

1. Adding Haskell/GHC signatures to the functions to see if it makes any
difference?
2. Is there any difference if you “grep qualif” in the two fq files?

- Ranjit.

**Comment by facundominguez** [comment]
Thanks! I think I found the difference by pruning the .fq files. It came down to this binding, where the later gets the constraints verified.
```diff
- bind 73 lq_anf$##7205759403792801143##d1XF : {lq_tmp$x##276 : int | [((lqdc##$select##GHC.Num.Integer.IS##1 lq_tmp$x##276) = lq_anf$##7205759403792801142##d1XE)]}
+ bind 73 lq_anf$##7205759403792801143##d1XF : {lq_tmp$x##276 : int | [(lq_tmp$x##276 = lq_anf$##7205759403792801142##d1XE)]}
```

**Comment by jazullo** [comment]
Hello. I am interested in seeing support for GHC 9.10.1 due to my own interests in linear let and where clauses. I was wondering about the state of support in general, and how I could try building it. I tried git-cloning the repository on the fd/ghc-9.10 branch and attempted cabal v2-build, but it yielded an error about not finding a specific version of ghc-9.9 despite being on the ghc-9.10 branch: https://gist.github.com/jazullo/e5fbcf3b266e7ecc8c1d22d7069a17c0

Additionally, I tried building my codebase while pinning the final commit of the GHC 9.10.1 branch as the Liquid Haskell version as a source-repository-package: 
```
source-repository-package
    type: git
    location: https://github.com/ucsd-progsys/liquidhaskell
    tag: 344b0ffff7a9b38ff63e4ff55da8c69b9a58bab4
    subdir: liquid-prelude liquidhaskell-boot
```
But this yielded a build error that is difficult to understand: https://gist.github.com/jazullo/39994cce3721a2c05c87ff61a38d66aa
We were thinking this may have to do with the non-transitivity of .cabal magic, but we are not sure. I would greatly appreciate a commit or a process that can readily be used to build with GHC 9.10.1 (I understand there may be some test cases that don't pass) or any insights into what could be causing my build errors. Thank you very much.

**Comment by facundominguez** [comment]
:wave: Those errors mean that definitions have moved elsewhere in GHC 9.10. While the testsuites aren't passing, some amount of debugging will be necessary to put LH into a usable state.

> but it yielded an error about not finding a specific version of ghc-9.9 despite being on the ghc-9.10

Yes, this is because when I started this work, GHC 9.10 wasn't released yet.

**Comment by jazullo** [comment]
Hello and thanks again, I was able to resolve the issues I was having by getting my `.cabal` and `.project` files right, mostly listing the right subdirectories (`subdir: liquid-prelude liquidhaskell-boot liquid-fixpoint .`) and eliminating the depreciated liquid libraries from my project file.

**Comment by facundominguez** [comment]
I fixed the [last issue](https://github.com/ucsd-progsys/liquidhaskell/issues/2307#issuecomment-2211181096) by tweaking annotations for `base`.

Now I'm facing another problem in `tests/pos/T1697.hs`. I get that a subtyping contraint is malformed because the Haskell type of the subtype doesn't match the Haskell type of the supertype.
```
forall a b ->
T1697.TaggedT user m a
-> (a -> T1697.TaggedT user m b) -> T1697.TaggedT user m b

 <: 

T1697.TaggedT user m a
-> (a -> T1697.TaggedT user m b) -> T1697.TaggedT user m b

   |
46 |   x >>= f = TaggedT (unTag x >>= \y -> unTag (f y))
   |     ^^^
```

That `forall a b ->` in the subtype seems necessary. The supertype is missing the same forall. Eliminating the `forall a b ->` from the subtype doesn't help, because `a` and `b` have different unique identifiers in the supertype. Since the types are compared via alpha equality, adding the missing foralls would fix it, but I don't know how to get those yet.

When looking at LH with ghc-9.8.2, though, this constraint isn't generated. I still have to understand why.

**Comment by facundominguez** [comment]
All remaining failures boiled down to definitions being moved to `ghc-internal`. All tests are passing now.

**Comment by ranjitjhala** [comment]
Fantastic!!!

- Ranjit.

**Comment by ranjitjhala** [comment]
Thanks @facundominguez !!! 🎉
