### ISSUE TITLE
Support for GHC 9.14?

### ISSUE THREAD

**Issue by ulysses4ever** [ucsd-progsys/liquidhaskell#2608]
I tried building the latest `liquidhaskell-boot` with GHC 9.14.1 with `--allow-newer`, and it, understandably fails.

```
Building library for liquidhaskell-boot-0.9.12.2...
[ 1 of 92] Compiling Language.Haskell.Liquid.CSS ( src/Language/Haskell/Liquid/CSS.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/CSS.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/CSS.dyn_o )
[ 2 of 92] Compiling Language.Haskell.Liquid.Cabal ( src/Language/Haskell/Liquid/Cabal.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/Cabal.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/Cabal.dyn_o )
[ 3 of 92] Compiling Language.Haskell.Liquid.GHC.Plugin.Tutorial ( src/Language/Haskell/Liquid/GHC/Plugin/Tutorial.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/GHC/Plugin/Tutorial.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/GHC/Plugin/Tutorial.dyn_o )
[ 4 of 92] Compiling Language.Haskell.Liquid.Misc ( src/Language/Haskell/Liquid/Misc.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/Misc.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/Misc.dyn_o )
[ 5 of 92] Compiling Language.Haskell.Liquid.Types.Generics ( src/Language/Haskell/Liquid/Types/Generics.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/Types/Generics.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/Types/Generics.dyn_o )
src/Language/Haskell/Liquid/Types/Generics.hs:19:10: warning: [GHC-62412] [-Wsimplifiable-class-constraints]
    • The constraint ‘Eq (Generically a)’ matches
        instance (Generic a, Eq (Rep a ())) => Eq (Generically a)
          -- Defined at src/Language/Haskell/Liquid/Types/Generics.hs:39:10
      This makes type inference for inner bindings fragile;
        either use MonoLocalBinds, or simplify it using the instance
    • In the instance declaration for ‘Hashable (Generically a)’
   |
19 | instance (Eq (Generically a), Generic a, GHashable Zero (Rep a)) => Hashable (Generically a) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[ 6 of 92] Compiling Language.Haskell.Liquid.UX.Config ( src/Language/Haskell/Liquid/UX/Config.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/UX/Config.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/UX/Config.dyn_o )
[ 7 of 92] Compiling Language.Haskell.Liquid.UX.SimpleVersion ( src/Language/Haskell/Liquid/UX/SimpleVersion.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/UX/SimpleVersion.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Language/Haskell/Liquid/UX/SimpleVersion.dyn_o )
[ 8 of 92] Compiling Liquid.GHC.API.Compat ( src-ghc-9.10/Liquid/GHC/API/Compat.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Liquid/GHC/API/Compat.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Liquid/GHC/API/Compat.dyn_o )
[ 9 of 92] Compiling Liquid.GHC.API.StableModule ( src-ghc/Liquid/GHC/API/StableModule.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Liquid/GHC/API/StableModule.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Liquid/GHC/API/StableModule.dyn_o )
[10 of 92] Compiling Liquid.GHC.API.Extra ( src-ghc/Liquid/GHC/API/Extra.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Liquid/GHC/API/Extra.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Liquid/GHC/API/Extra.dyn_o )
src-ghc/Liquid/GHC/API/Extra.hs:41:65: warning: [GHC-61689] [-Wdodgy-imports]
    Module ‘GHC.Core.Type’ does not export ‘isPredTy’.
   |
41 | import GHC.Core.Type                  as Ghc hiding (typeKind , isPredTy, extendCvSubst, linear)
   |                                                                 ^^^^^^^^

[11 of 92] Compiling Liquid.GHC.API   ( src-ghc/Liquid/GHC/API.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Liquid/GHC/API.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Liquid/GHC/API.dyn_o )
src-ghc/Liquid/GHC/API.hs:333:7: error: [GHC-61689]
    Module ‘GHC.Core.Predicate’ does not export ‘isEvVarType’.
    Suggested fix: Perhaps use ‘isCoVarType’
    |
333 |     , isEvVarType
    |       ^^^^^^^^^^^

src-ghc/Liquid/GHC/API.hs:337:7: error: [GHC-61689]
    Module ‘GHC.Core.Predicate’ does not export ‘isNomEqPred’.
    Suggested fix: Perhaps use one of these: ‘mkNomEqPred’, ‘isEqPred’
    |
337 |     , isNomEqPred
    |       ^^^^^^^^^^^

src-ghc/Liquid/GHC/API.hs:517:47: error: [GHC-61689]
    Module ‘GHC.Tc.Gen.App’ does not export ‘tcInferSigma’.
    |
517 | import GHC.Tc.Gen.App                 as Ghc (tcInferSigma)
    |                                               ^^^^^^^^^^^^

src-ghc/Liquid/GHC/API.hs:782:7: error: [GHC-61689]
    Module ‘GHC.Unit.Home.ModInfo’ does not export ‘HomePackageTable’.
    |
782 |     ( HomePackageTable, HomeModInfo(hm_iface), lookupHpt )
    |       ^^^^^^^^^^^^^^^^

src-ghc/Liquid/GHC/API.hs:782:48: error: [GHC-61689]
    Module ‘GHC.Unit.Home.ModInfo’ does not export ‘lookupHpt’.
    |
782 |     ( HomePackageTable, HomeModInfo(hm_iface), lookupHpt )
    |                                                ^^^^^^^^^

[88 of 92] Compiling Paths_liquidhaskell_boot ( dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/autogen/Paths_liquidhaskell_boot.hs, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Paths_liquidhaskell_boot.o, dist-newstyle/build/x86_64-linux/ghc-9.14.1/liquidhaskell-boot-0.9.12.2/build/Paths_liquidhaskell_boot.dyn_o )
Error: [Cabal-7125]
Failed to build liquidhaskell-boot-0.9.12.2.
```

**Comment by facundominguez** [comment]
There is work in progress in #2604. We have all the patches, but they still need to be put together in one branch and CI needs to be updated to use GHC 9.14.

**Comment by facundominguez** [comment]
#2604 was merged 🙌

**Comment by facundominguez** [comment]
A release that works with ghc 9.14.1 is going to require dependencies to update their dependency bounds still.

**Comment by ulysses4ever** [comment]
cool, thanks! is there a convenient open channel where I can track LH releases? (besides Hackage RSS feed :-)). If not, I'd appreciate ping on this thread. But that's not critical. I just need to get back to stackage people when there's a release supporting 9.14.

**Comment by facundominguez** [comment]
👋 `liquidhaskell-0.9.14.1` is out.

**Comment by ulysses4ever** [comment]
nice, thank you! I pinged stackage people https://github.com/commercialhaskell/stackage/issues/7917#issuecomment-4390132251
