### ISSUE TITLE
Liquid Haskell Installation Issue

### ISSUE THREAD

**Issue by Abhiroop** [ucsd-progsys/liquidhaskell#2514]
I am using these versions of GHC and cabal:

```
 $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.6.7
$ cabal --version
cabal-install version 3.12.1.0
compiled using version 3.12.1.0 of the Cabal library
```

My cabal file has the following:

```
executable WasP
    main-is:          Main.hs
    build-depends:    base >=4.16.4.0 && <4.19,
                      containers >= 0.6.5.1,
                      mtl >= 2.2.2,
                      text >= 2.1.1,
                      transformers >= 0.5.6.2,
                      liquidhaskell
    hs-source-dirs:   app
    default-language: Haskell2010
```

when I do `cabal build` on this I get the following:

```
Starting     liquidhaskell-0.8.6.2 (lib)
Building     liquidhaskell-0.8.6.2 (lib)

Failed to build liquidhaskell-0.8.6.2.
Build log (
/home/abhiroop/.cabal/logs/ghc-9.6.7/liquidhaskell-0.8.6.2-27136e346b4fa72d26f85b5f871558bbc5961a9b475a7e58a9f85bbf11d5348c.log
):
Warning: liquidhaskell.cabal:48:28: Packages with 'cabal-version: 1.12' or
later should specify a specific version of the Cabal spec of the form
'cabal-version: x.y'. Use 'cabal-version: 1.22'.
Configuring library for liquidhaskell-0.8.6.2...
Preprocessing library for liquidhaskell-0.8.6.2...
Building library for liquidhaskell-0.8.6.2...
[ 1 of 90] Compiling Gradual.GUI.Misc ( src/Gradual/GUI/Misc.hs, dist/build/Gradual/GUI/Misc.o, dist/build/Gradual/GUI/Misc.dyn_o )
[ 2 of 90] Compiling Gradual.Misc     ( src/Gradual/Misc.hs, dist/build/Gradual/Misc.o, dist/build/Gradual/Misc.dyn_o )
[ 3 of 90] Compiling Gradual.Trivial  ( src/Gradual/Trivial.hs, dist/build/Gradual/Trivial.o, dist/build/Gradual/Trivial.dyn_o )
[ 4 of 90] Compiling Language.Haskell.Liquid.Bag ( include/Language/Haskell/Liquid/Bag.hs, dist/build/Language/Haskell/Liquid/Bag.o, dist/build/Language/Haskell/Liquid/Bag.dyn_o )
[ 5 of 90] Compiling Language.Haskell.Liquid.Equational ( include/Language/Haskell/Liquid/Equational.hs, dist/build/Language/Haskell/Liquid/Equational.o, dist/build/Language/Haskell/Liquid/Equational.dyn_o )
[ 6 of 90] Compiling Language.Haskell.Liquid.Foreign ( include/Language/Haskell/Liquid/Foreign.hs, dist/build/Language/Haskell/Liquid/Foreign.o, dist/build/Language/Haskell/Liquid/Foreign.dyn_o )
[ 7 of 90] Compiling Language.Haskell.Liquid.GHC.API ( src/Language/Haskell/Liquid/GHC/API.hs, dist/build/Language/Haskell/Liquid/GHC/API.o, dist/build/Language/Haskell/Liquid/GHC/API.dyn_o )

src/Language/Haskell/Liquid/GHC/API.hs:6:1: error:
    Could not find module ‘ConLike’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
6 | import ConLike        as Ghc
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:7:1: error:
    Could not find module ‘Var’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
7 | import Var            as Ghc
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:8:1: error:
    Could not find module ‘Module’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
8 | import Module         as Ghc
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:9:1: error:
    Could not find module ‘DataCon’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
9 | import DataCon        as Ghc
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:10:1: error:
    Could not find module ‘TysWiredIn’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
10 | import TysWiredIn     as Ghc  
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:11:1: error:
    Could not find module ‘BasicTypes’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
11 | import BasicTypes     as Ghc 
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:12:1: error:
    Could not find module ‘CoreSyn’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
12 | import CoreSyn        as Ghc hiding (AnnExpr, AnnExpr' (..), AnnRec, AnnCase) 
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:13:1: error:
    Could not find module ‘TyCon’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
13 | import TyCon          as Ghc 
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:14:1: error:
    Could not find module ‘NameSet’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
14 | import NameSet        as Ghc
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:15:1: error:
    Could not find module ‘InstEnv’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
15 | import InstEnv        as Ghc 
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:16:1: error:
    Could not find module ‘Type’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
16 | import Type           as Ghc hiding (typeKind) 
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:17:1: error:
    Could not find module ‘TyCoRep’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
17 | import TyCoRep        as Ghc 
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:18:1: error:
    Could not find module ‘Class’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
18 | import Class          as Ghc
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:19:1: error:
    Could not find module ‘Unique’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
19 | import Unique         as Ghc
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:20:1: error:
    Could not find module ‘RdrName’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
20 | import RdrName        as Ghc
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:21:1: error:
    Could not find module ‘SrcLoc’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
21 | import SrcLoc         as Ghc 
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:22:1: error:
    Could not find module ‘Name’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
22 | import Name           as Ghc hiding (varName) 
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:28:1: error:
    Could not find module ‘TysPrim’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
28 | import TysPrim        as Ghc
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:29:1: error:
    Could not find module ‘HscTypes’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
29 | import HscTypes       as Ghc
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:30:1: error:
    Could not find module ‘HscMain’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
30 | import HscMain        as Ghc 
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/API.hs:31:1: error:
    Could not find module ‘Id’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
31 | import Id             as Ghc hiding (lazySetIdInfo, setIdExported, setIdNotExported) 
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 8 of 90] Compiling Language.Haskell.Liquid.List ( include/Language/Haskell/Liquid/List.hs, dist/build/Language/Haskell/Liquid/List.o, dist/build/Language/Haskell/Liquid/List.dyn_o )
[ 9 of 90] Compiling Language.Haskell.Liquid.Prelude ( include/Language/Haskell/Liquid/Prelude.hs, dist/build/Language/Haskell/Liquid/Prelude.o, dist/build/Language/Haskell/Liquid/Prelude.dyn_o )
[10 of 90] Compiling Language.Haskell.Liquid.ProofCombinators ( include/Language/Haskell/Liquid/ProofCombinators.hs, dist/build/Language/Haskell/Liquid/ProofCombinators.o, dist/build/Language/Haskell/Liquid/ProofCombinators.dyn_o )
[11 of 90] Compiling Language.Haskell.Liquid.Types.Names ( src/Language/Haskell/Liquid/Types/Names.hs, dist/build/Language/Haskell/Liquid/Types/Names.o, dist/build/Language/Haskell/Liquid/Types/Names.dyn_o )
[12 of 90] Compiling Language.Haskell.Liquid.Types.Variance ( src/Language/Haskell/Liquid/Types/Variance.hs, dist/build/Language/Haskell/Liquid/Types/Variance.o, dist/build/Language/Haskell/Liquid/Types/Variance.dyn_o )
[13 of 90] Compiling Language.Haskell.Liquid.UX.Config ( src/Language/Haskell/Liquid/UX/Config.hs, dist/build/Language/Haskell/Liquid/UX/Config.o, dist/build/Language/Haskell/Liquid/UX/Config.dyn_o )
[14 of 90] Compiling Gradual.Types    ( src/Gradual/Types.hs, dist/build/Gradual/Types.o, dist/build/Gradual/Types.dyn_o )
[15 of 90] Compiling Gradual.Uniquify ( src/Gradual/Uniquify.hs, dist/build/Gradual/Uniquify.o, dist/build/Gradual/Uniquify.dyn_o )

src/Gradual/Uniquify.hs:110:27: error: [GHC-83865]
    • Expecting one more argument to ‘BindEnv’
      Expected a type, but ‘BindEnv’ has kind ‘* -> *’
    • In the type ‘BindEnv’
      In the definition of data constructor ‘UniqueST’
      In the data declaration for ‘UniqueST’
    |
110 |              , benv    :: BindEnv
    |                           ^^^^^^^
[16 of 90] Compiling Gradual.Refinements ( src/Gradual/Refinements.hs, dist/build/Gradual/Refinements.o, dist/build/Gradual/Refinements.dyn_o )

src/Gradual/Refinements.hs:12:37: error:
    Module
    ‘Language.Fixpoint.SortCheck’
    does not export
    ‘exprSort_maybe’
   |
12 | import Language.Fixpoint.SortCheck (exprSort_maybe)
   |                                     ^^^^^^^^^^^^^^
[17 of 90] Compiling Gradual.Concretize ( src/Gradual/Concretize.hs, dist/build/Gradual/Concretize.o, dist/build/Gradual/Concretize.dyn_o )

src/Gradual/Concretize.hs:25:14: error: [GHC-83865]
    • Expecting one more argument to ‘BindEnv’
      Expected a type, but ‘BindEnv’ has kind ‘* -> *’
    • In the type signature: gsubst :: (BindEnv, GSub GWInfo) -> a -> a
      In the class declaration for ‘GSubable’
   |
25 |   gsubst :: (BindEnv, GSub GWInfo) -> a -> a 
   |              ^^^^^^^
[18 of 90] Compiling Paths_liquidhaskell ( dist/build/autogen/Paths_liquidhaskell.hs, dist/build/Paths_liquidhaskell.o, dist/build/Paths_liquidhaskell.dyn_o )
[19 of 90] Compiling Language.Haskell.Liquid.Misc ( src/Language/Haskell/Liquid/Misc.hs, dist/build/Language/Haskell/Liquid/Misc.o, dist/build/Language/Haskell/Liquid/Misc.dyn_o )
[20 of 90] Compiling Language.Haskell.Liquid.Types.Errors ( src/Language/Haskell/Liquid/Types/Errors.hs, dist/build/Language/Haskell/Liquid/Types/Errors.o, dist/build/Language/Haskell/Liquid/Types/Errors.dyn_o )

src/Language/Haskell/Liquid/Types/Errors.hs:50:1: error:
    Could not find module ‘SrcLoc’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
50 | import           SrcLoc                      
   | ^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/Types/Errors.hs:51:1: error:
    Could not find module ‘FastString’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
51 | import           FastString
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/Types/Errors.hs:52:1: error:
    Could not find module ‘HscTypes’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
52 | import           HscTypes (srcErrorMessages, SourceError)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/Types/Errors.hs:53:1: error:
    Could not find module ‘ErrUtils’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
53 | import           ErrUtils
   | ^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/Liquid/Types/Errors.hs:54:1: error:
    Could not find module ‘Bag’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
54 | import           Bag
   | ^^^^^^^^^^^^^^^^^^^^
Error: [Cabal-7125]
Failed to build liquidhaskell-0.8.6.2 (which is required by exe:myapp from myapp-0.1.0.0). See the build log above for details.
```

Could someone help me figure out what I am doing wrong?

**Comment by facundominguez** [comment]
👋 You would need to convince `cabal` to use a newer `liquidhaskell`. I think your compiler version might work with `liquidhaskell-0.9.6.3.1`. I fiddled with hackage revisions. Running `cabal update` and retrying the build might work.

Alternatively, you could try using a newer compiler or passing `--constraint="liquidhaskell==0.9.6.3.1"` to `cabal`.

**Comment by Abhiroop** [comment]
Thanks! I moved to the latest GHC (9.12.2) and cabal (3.14.2.0) to get it working.
