### PR TITLE
Optimize and document (?)

### LINKED ISSUE #2544: Exponential growth of constraints on the number of lemma applications
The following example passes verification:
```Haskell
{-@ LIQUID "--exactdc" @-}
module Test where

import Language.Haskell.Liquid.ProofCombinators

{-@
f :: xs:[a]
  -> ys:[a]
  -> zs:[a]
  -> ws:[a]
  -> vs:[a]
  -> us:[a]
  -> { append xs (append ys (append zs (append ws (append vs us)))) =
       append (append (append (append (append xs ys) zs) ws) vs) us
     }
@-}
f :: [a] -> [a] -> [a] -> [a] -> [a] -> [a] -> ()
f xs ys zs ws vs us =
  () ? lemmaAssoc xs ys zs                                      --   1 constraint, 2 kvars
     ? lemmaAssoc xs ys (append zs (append ws (append vs us)))  --  65 constraints, 4 kvars
     ? lemmaAssoc (append xs ys) zs (append ws (append vs us))  -- 213 constraints, 6 kvars
     ? lemmaAssoc (append (append xs ys) zs) ws (append vs us)  -- 477 constraints, 8 kvars
     ? lemmaAssoc (append (append (append xs ys) zs) ws) vs us  -- 889 constraints, 10 kvars

{-@
assume lemmaAssoc
  :: xs:[a]
  -> ys:[a]
  -> zs:[a]
  -> { append xs (append ys zs) = append (append xs ys) zs}
@-}
lemmaAssoc :: [a] -> [a] -> [a] -> ()
lemmaAssoc _ _ _ = ()

append :: [a] -> [a] -> [a]
append [] ys = ys
append (x:xs) ys = x : append xs ys

{-@ reflect append @-}
```
LH reports 889 constraints were verified, and the fqout file shows 10 kvars.

If I comment the last application of `lemmaAssoc` the constraints drop roughly by half, although verification starts to fail, of course. The kvars also diminished as noted in the commments. Every time a lemma application is commented out the number of constraints halves again.

This doesn't look good for two reasons:
1. There is no inference of refinement types that could help verifying `f`, so introducing kvars doesn't seem to serve any purpose.
2. The exponential growth of constraints has a serious impact on performance in larger examples with 130 kvars and 56000 constraints.

Can we somehow cut on the number of kvars or checked constraints when introducing lemma applications?

### LINKED ISSUE #2617: Document `?` type signature a bit more
Removing the refinement type signature of `?`

```diff
-  {-@ (?) :: forall a b <pa :: a -> Bool, pb :: b -> Bool>. a<pa> -> b<pb> -> a<pa> @-}                                                                                                                
   (?) :: a -> b -> a                                                                                                                                                                                  
   x ? _ = x
```

causes only one test to fail: T1660, introduced in #1660. Error messages:

<details>

```
**** LIQUID: UNSAFE (8 constraints checked) ************************************
pos/T1660.hs:35:3: error:
    Liquid Type Mismatch
    .
    The inferred type
      VV : {v : (T1660.EqT a) | GHC.Internal.Types.True
                                && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.Admit
                                && not GHC.Internal.Types.False
                                && not (Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.QED)
                                && lq_anf$##7205759403792801613##d25f == T1660.id
                                && lq_anf$##7205759403792801614##d25g == T1660.fmap lq_anf$##7205759403792801613##d25f
                                && lq_anf$##7205759403792801615##d25h == T1660.id
                                && lq_anf$##7205759403792801616##d25i == T1660.id
                                && lq_anf$##7205759403792801617##d25j == T1660.fmap lq_anf$##7205759403792801616##d25i r##a1Sm
                                && lq_anf$##7205759403792801618##d25k == r##a1Sm
                                && lq_anf$##7205759403792801618##d25k == T1660.id r##a1Sm
                                && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.Admit == true
                                && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.QED == false
                                && T1660.id r##a1Sm == r##a1Sm
                                && lqdc##$select##T1660.EqSMT##3 v == GHC.Internal.Tuple.()
                                && T1660.id r##a1Sm ?a == T1660.id (r##a1Sm ?a)
                                && (exists [lq_anf$##7205759403792801619##d25l : func(0 , [a##a22T;
                                                                                           a##a22T]),
                                            lq_anf$##7205759403792801620##d25m : a##xo,
                                            lq_anf$##7205759403792801621##d25n : a##xo,
                                            lq_anf$##7205759403792801622##d25o : Tuple0,
                                            lq_anf$##7205759403792801623##d25p : a##xo]
                                      . T1660.eqT lq_anf$##7205759403792801620##d25m lq_anf$##7205759403792801623##d25p
                                        && v == T1660.EqSMT lq_anf$##7205759403792801620##d25m lq_anf$##7205759403792801623##d25p GHC.Internal.Tuple.()
                                        && lq_anf$##7205759403792801619##d25l == T1660.id
                                        && lq_anf$##7205759403792801620##d25m == lq_anf$##7205759403792801619##d25l (r##a1Sm ?a)
                                        && lq_anf$##7205759403792801620##d25m == T1660.fmap lq_anf$##7205759403792801619##d25l r##a1Sm ?a
                                        && lq_anf$##7205759403792801621##d25n == T1660.id r##a1Sm ?a
                                        && lq_anf$##7205759403792801622##d25o == T1660.lemmaId r##a1Sm ?a
                                        && lq_anf$##7205759403792801623##d25p == Language.Haskell.Liquid.ProofCombinators.? lq_anf$##7205759403792801621##d25n lq_anf$##7205759403792801622##d25o
                                        && lqdc##$select##T1660.EqSMT##1 v == lq_anf$##7205759403792801620##d25m
                                        && lqdc##$select##T1660.EqSMT##2 v == lq_anf$##7205759403792801623##d25p)
                                && (exists [lq_anf$##7205759403792801624##d25q : func(0 , [r##a22U;
                                                                                           (T1660.EqT a##a22T)])]
                                      . lq_anf$##7205759403792801624##d25q == lam lam_arg##1 : r##a22U . T1660.EqSMT (T1660.fmap T1660.id r##a1Sm lam_arg##1) (Language.Haskell.Liquid.ProofCombinator
s.? (T1660.id r##a1Sm lam_arg##1) (T1660.lemmaId r##a1Sm lam_arg##1)) GHC.Internal.Tuple.())}
    .
    is not a subtype of the required type
      VV : {VV##2045 : (T1660.EqT a) | T1660.eqT (lq_anf$##7205759403792801617##d25j ?a) (lq_anf$##7205759403792801618##d25k ?a)}
    .
    in the context
      ?a : a
    Constraint id 26
   |
35 |   (\r -> EqFun (fmap id r) (id r)
   |

pos/T1660.hs:36:54: error:
    Liquid Type Mismatch
    .
    The inferred type
      VV : {v : () | v == GHC.Internal.Tuple.()}
    .
    is not a subtype of the required type
      VV : {VV##2067 : () | ?a == Language.Haskell.Liquid.ProofCombinators.? (T1660.id r##a1Sm a##a1Sn) ?c}
    .
    in the context
      a##a1Sn : {VV : a | GHC.Internal.Types.True
                          && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.Admit
                          && not GHC.Internal.Types.False
                          && not (Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.QED)
                          && lq_anf$##7205759403792801613##d25f == T1660.id
                          && lq_anf$##7205759403792801614##d25g == T1660.fmap lq_anf$##7205759403792801613##d25f
                          && lq_anf$##7205759403792801615##d25h == T1660.id
                          && lq_anf$##7205759403792801616##d25i == T1660.id
                          && lq_anf$##7205759403792801617##d25j == T1660.fmap lq_anf$##7205759403792801616##d25i r##a1Sm
                          && lq_anf$##7205759403792801618##d25k == r##a1Sm
                          && lq_anf$##7205759403792801618##d25k == T1660.id r##a1Sm
                          && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.Admit == true
                          && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.QED == false
                          && T1660.id r##a1Sm == r##a1Sm
                          && (exists [lq_anf$##7205759403792801624##d25q : func(0 , [r##a22U;
                                                                                     (T1660.EqT a##a22T)])]
                                . lq_anf$##7205759403792801624##d25q == lam lam_arg##1 : a##xo . T1660.EqSMT (T1660.fmap T1660.id r##a1Sm lam_arg##1) (Language.Haskell.Liquid.ProofCombinators.? (T1660.id r##a1Sm lam_arg##1) (T1660.lemmaId r##a1Sm lam_arg##1)) GHC.Internal.Tuple.())}
       
      ?c : {?c : () | ?c == T1660.lemmaId r##a1Sm a##a1Sn
                      && T1660.id r##a1Sm a##a1Sn == T1660.id (r##a1Sm a##a1Sn)}
       
      ?a : {VV : a | VV == lq_anf$##7205759403792801619##d25l (r##a1Sm a##a1Sn)
                     && VV == T1660.fmap lq_anf$##7205759403792801619##d25l r##a1Sm a##a1Sn}
    Constraint id 30
   |
36 |     (\a -> EqSMT (fmap id r a) (id r a? lemmaId r a) ()))
   | 
```

</details>

The comments surrounding the definition of `?` are insufficient to understand the effects of adding the abstract refinement predicates `pa` and `pb`.

This ticket is to ask for some more explanation and to elucidate what is special about T1660 that requires this refinement type.

### PR DESCRIPTION
**Pull request by facundominguez**
This PR introduces a core pass which runs after ANF normalization and before constraint generation. It replaces fully-applied `(?) @A @b e1 e2` expressions with just `e1`.

The pass looks up (?) in the GlobalRdrEnv (tcg_rdr_env) to obtain its Name, then uses Name equality for fast identification in Core. If the module does not have (?) in scope, the pass is skipped entirely.

This avoids introducing KVars for the applications of (?), while the lemma argument (e2) remains as an ANF binding so its postcondition still enters the verification environment.

This eliminates the growth of queries for the SMT solver with each (?) application without --reflection and makes T1660 independent of (?)'s LH signature.

A second commit documents (?) and eliminates the now redundant refinement type signature.

Fixes #2544.
Fixes #2617.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Amazing I bet this will improve performance in other benchmarks too!

**Comment by facundominguez** [comment]
Some tests improve, indeed. I guess we don't see more of a difference because there are not that many uses of `?` without `--reflection`.

top
bot
