### ISSUE TITLE
Name resolution chockes on depednent functions

### ISSUE THREAD

**Issue by AlecsFerra** [ucsd-progsys/liquidhaskell#2626]
**Describe the bug**
For some reason the following program is rejected during name resolution

**To Reproduce**
```hs
{-# OPTIONS_GHC -fplugin=LiquidHaskell #-}

module Foo where

import Data.Void
import Language.Haskell.Liquid.ProofCombinators

-- Tarski universe codes
{-@ LIQUID "--no-positivity-check" @-}
data U where
  Zero :: U
  One  :: U
{-@ Pi :: s:U -> (Ix ElU s -> U) -> U @-}
  Pi   ::   U -> (ElU      -> U) -> U

-- Eliminator
{-@ stratified ElU @-}
data ElU where
{-@ ElZero :: Void -> Ix ElU Zero @-}
  ElZero   :: Void -> ElU
{-@ ElOne :: ()   -> Ix ElU One @-}
  ElOne   :: ()   -> ElU
{-@ ElPi :: s:U -> r:(Ix ElU s -> U) -> (a:Ix ElU s -> Ix ElU (r a)) -> Ix ElU (Pi s r) @-}
  ElPi   ::   U ->   (ElU      -> U) -> (  ElU      -> ElU)          -> ElU

```

Error:
```sh
    Illegal type specification for `Foo.ElPi`
    Foo.ElPi :: s:Foo.U -> r:(lq_tmp$db##0:{VV : Foo.ElU | Language.Haskell.Liquid.ProofCombinators.prop VV == s} -> Foo.U) -> lq_tmp$db##2:(a:{VV : Foo.ElU | Language.Haskell.Liquid.ProofCombinators.prop VV == s} -> {VV : Foo.ElU | Language.Haskell.Liquid.ProofCombinators.prop VV == r a}) -> {VV : Foo.ElU | Language.Haskell.Liquid.ProofCombinators.prop VV == Foo.Pi s r}
    Sort Error in Refinement: {VV : Foo.ElU | Language.Haskell.Liquid.ProofCombinators.prop VV == r a}
    Unbound symbol r --- perhaps you meant: s, a ?
    Just
   |
23 | {-@ ElPi :: s:U -> r:(Ix ElU s -> U) -> (a:Ix ElU s -> Ix ElU (r a)) -> Ix ElU (Pi s r) @-}
```

**Expected behavior**
The stratification check should reject the definition

**Desktop (please complete the following information):**
 - OS/Distro: [e.g. windows, ubuntu, nixos]
 - GHC version
 - Liquid Haskell version

**Additional context**
Add here other relevant information about the problem if any. e.g. test files and build configuration files, or links to an example repository.

**Comment by AlecsFerra** [comment]
It looks like the usual bug with refined dependent pairs but there are no dependent pairs now, also if we replace `r a` with for example Zero then it will complain about `Pi` not being in scope

**Comment by facundominguez** [comment]
This brings `r` into scope:
```
--- a/liquidhaskell-boot/src/Language/Haskell/Liquid/Types/RTypeOp.hs
+++ b/liquidhaskell-boot/src/Language/Haskell/Liquid/Types/RTypeOp.hs
@@ -590,7 +590,7 @@ efoldReft logicBind bsc cb dty g f fp = go
          c  = f γ (Just me) r (go (insertsSEnv γ (cb c ts)) (go' γ z ts) t')
     go γ z me@(RFun x _ t t' r)
        | logicBind x t                  = f γ (Just me) r (go γ' (go γ z t) t')
-       | otherwise                      = f γ (Just me) r (go γ  (go γ z t) t')
+       | otherwise                      = f γ (Just me) r (go γ' (go γ z t) t')
        where
          γ'                             = insertSEnv x (g t) γ
     go γ z me@(RApp _ ts rs r)          = f γ (Just me) r (ho' γ (go' γ' z ts) rs)
```

I don't know what the `logicBind` guard is accomplishing.

But the test still fails because Pi is not in scope yet.

**Comment by facundominguez** [comment]
`--exact-data-cons` brings `Pi` into scope.

The `logicBind` guard was introduced in #685. No test fails if I remove the `logicBind` guard, except for `tests/errors/HigherOrderBinder.hs`, which stops failing of an unbound identifier, and starts failing because function `foo` doesn't pass verification.

```
tests/errors/HigherOrderBinder.hs:7:1: error:
    Liquid Type Mismatch
    .
    The inferred type
      VV : GHC.Internal.Types.Int
    .
    is not a subtype of the required type
      VV : {VV##643 : GHC.Internal.Types.Int | VV##643 == 123 + f##aEg a##aEf}
    .
    in the context
      a##aEf : GHC.Internal.Types.Int
    Constraint id 3
  |
7 | foo a f = f a
  | ^^^^^^^^^^^^^
```

@nikivazou, do you have some example to motivate `logicBind` nowadays?

**Comment by facundominguez** [comment]
`--higherorder` also brings `r` into scope without removing `logicBind`. However, I find the error message too confusing to leave it as is.

**Comment by AlecsFerra** [comment]
My proposal is enabling most of the flags by default, or at least have a single flag that enable all the modern lh features

**Comment by nikivazou** [comment]
I agree with the proposal. If we have reflection on we definitely need the `--higherorder` bind on (so that high order arguments get into scope). 

Maybe not PLE though, because it might make verification time much slow?

**Comment by AlecsFerra** [comment]
> Maybe not PLE though, because it might make verification time much slow?

Is this actually the case? Every goal should be discharged at the 0th iteration of the PLE algorithm, since every iteration we check if the negation of the goal is sat (so in theoretically nearly zero extra work done)

**Comment by facundominguez** [comment]
There is #2292 to record my experience when I tried to make `--exact-data-cons` the default. I tried it today once more and the `liquidhaskell` package failed to build.

**Comment by nikivazou** [comment]
The `exact-data-cons` was developed before we encoded data types are STM data types. 
And the logic bind was to bring higher order binders into the logical scope that seems to be shadowed by the `--higherorder`. 
We can definitely remove/merge things.
