### ISSUE TITLE
Document `?` type signature a bit more

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#2617]
Removing the refinement type signature of `?`

```diff
-  {-@ (?) :: forall a b <pa :: a -> Bool, pb :: b -> Bool>. a<pa> -> b<pb> -> a<pa> @-}                                                                                                                
   (?) :: a -> b -> a                                                                                                                                                                                  
   x ? _ = x
```

causes only one test to fail: T1660, introduced in #1660. Error messages:

<details>

```
**** LIQUID: UNSAFE (8 constraints checked) ************************************
pos/T1660.hs:35:3: error:
    Liquid Type Mismatch
    .
    The inferred type
      VV : {v : (T1660.EqT a) | GHC.Internal.Types.True
                                && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.Admit
                                && not GHC.Internal.Types.False
                                && not (Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.QED)
                                && lq_anf$##7205759403792801613##d25f == T1660.id
                                && lq_anf$##7205759403792801614##d25g == T1660.fmap lq_anf$##7205759403792801613##d25f
                                && lq_anf$##7205759403792801615##d25h == T1660.id
                                && lq_anf$##7205759403792801616##d25i == T1660.id
                                && lq_anf$##7205759403792801617##d25j == T1660.fmap lq_anf$##7205759403792801616##d25i r##a1Sm
                                && lq_anf$##7205759403792801618##d25k == r##a1Sm
                                && lq_anf$##7205759403792801618##d25k == T1660.id r##a1Sm
                                && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.Admit == true
                                && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.QED == false
                                && T1660.id r##a1Sm == r##a1Sm
                                && lqdc##$select##T1660.EqSMT##3 v == GHC.Internal.Tuple.()
                                && T1660.id r##a1Sm ?a == T1660.id (r##a1Sm ?a)
                                && (exists [lq_anf$##7205759403792801619##d25l : func(0 , [a##a22T;
                                                                                           a##a22T]),
                                            lq_anf$##7205759403792801620##d25m : a##xo,
                                            lq_anf$##7205759403792801621##d25n : a##xo,
                                            lq_anf$##7205759403792801622##d25o : Tuple0,
                                            lq_anf$##7205759403792801623##d25p : a##xo]
                                      . T1660.eqT lq_anf$##7205759403792801620##d25m lq_anf$##7205759403792801623##d25p
                                        && v == T1660.EqSMT lq_anf$##7205759403792801620##d25m lq_anf$##7205759403792801623##d25p GHC.Internal.Tuple.()
                                        && lq_anf$##7205759403792801619##d25l == T1660.id
                                        && lq_anf$##7205759403792801620##d25m == lq_anf$##7205759403792801619##d25l (r##a1Sm ?a)
                                        && lq_anf$##7205759403792801620##d25m == T1660.fmap lq_anf$##7205759403792801619##d25l r##a1Sm ?a
                                        && lq_anf$##7205759403792801621##d25n == T1660.id r##a1Sm ?a
                                        && lq_anf$##7205759403792801622##d25o == T1660.lemmaId r##a1Sm ?a
                                        && lq_anf$##7205759403792801623##d25p == Language.Haskell.Liquid.ProofCombinators.? lq_anf$##7205759403792801621##d25n lq_anf$##7205759403792801622##d25o
                                        && lqdc##$select##T1660.EqSMT##1 v == lq_anf$##7205759403792801620##d25m
                                        && lqdc##$select##T1660.EqSMT##2 v == lq_anf$##7205759403792801623##d25p)
                                && (exists [lq_anf$##7205759403792801624##d25q : func(0 , [r##a22U;
                                                                                           (T1660.EqT a##a22T)])]
                                      . lq_anf$##7205759403792801624##d25q == lam lam_arg##1 : r##a22U . T1660.EqSMT (T1660.fmap T1660.id r##a1Sm lam_arg##1) (Language.Haskell.Liquid.ProofCombinator
s.? (T1660.id r##a1Sm lam_arg##1) (T1660.lemmaId r##a1Sm lam_arg##1)) GHC.Internal.Tuple.())}
    .
    is not a subtype of the required type
      VV : {VV##2045 : (T1660.EqT a) | T1660.eqT (lq_anf$##7205759403792801617##d25j ?a) (lq_anf$##7205759403792801618##d25k ?a)}
    .
    in the context
      ?a : a
    Constraint id 26
   |
35 |   (\r -> EqFun (fmap id r) (id r)
   |

pos/T1660.hs:36:54: error:
    Liquid Type Mismatch
    .
    The inferred type
      VV : {v : () | v == GHC.Internal.Tuple.()}
    .
    is not a subtype of the required type
      VV : {VV##2067 : () | ?a == Language.Haskell.Liquid.ProofCombinators.? (T1660.id r##a1Sm a##a1Sn) ?c}
    .
    in the context
      a##a1Sn : {VV : a | GHC.Internal.Types.True
                          && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.Admit
                          && not GHC.Internal.Types.False
                          && not (Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.QED)
                          && lq_anf$##7205759403792801613##d25f == T1660.id
                          && lq_anf$##7205759403792801614##d25g == T1660.fmap lq_anf$##7205759403792801613##d25f
                          && lq_anf$##7205759403792801615##d25h == T1660.id
                          && lq_anf$##7205759403792801616##d25i == T1660.id
                          && lq_anf$##7205759403792801617##d25j == T1660.fmap lq_anf$##7205759403792801616##d25i r##a1Sm
                          && lq_anf$##7205759403792801618##d25k == r##a1Sm
                          && lq_anf$##7205759403792801618##d25k == T1660.id r##a1Sm
                          && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.Admit == true
                          && Language.Haskell.Liquid.ProofCombinators.isAdmit Language.Haskell.Liquid.ProofCombinators.QED == false
                          && T1660.id r##a1Sm == r##a1Sm
                          && (exists [lq_anf$##7205759403792801624##d25q : func(0 , [r##a22U;
                                                                                     (T1660.EqT a##a22T)])]
                                . lq_anf$##7205759403792801624##d25q == lam lam_arg##1 : a##xo . T1660.EqSMT (T1660.fmap T1660.id r##a1Sm lam_arg##1) (Language.Haskell.Liquid.ProofCombinators.? (T1660.id r##a1Sm lam_arg##1) (T1660.lemmaId r##a1Sm lam_arg##1)) GHC.Internal.Tuple.())}
       
      ?c : {?c : () | ?c == T1660.lemmaId r##a1Sm a##a1Sn
                      && T1660.id r##a1Sm a##a1Sn == T1660.id (r##a1Sm a##a1Sn)}
       
      ?a : {VV : a | VV == lq_anf$##7205759403792801619##d25l (r##a1Sm a##a1Sn)
                     && VV == T1660.fmap lq_anf$##7205759403792801619##d25l r##a1Sm a##a1Sn}
    Constraint id 30
   |
36 |     (\a -> EqSMT (fmap id r a) (id r a? lemmaId r a) ()))
   | 
```

</details>

The comments surrounding the definition of `?` are insufficient to understand the effects of adding the abstract refinement predicates `pa` and `pb`.

This ticket is to ask for some more explanation and to elucidate what is special about T1660 that requires this refinement type.

**Comment by ranjitjhala** [comment]
I should do this, since I think this whole business was my doing. Here's what's happening.

In "vanilla" LH, we often want to instantiate type variables with refinements, for example consider the program

```haskell
safeHead :: a -> [a] -> a
safeHead def [] = def 
safeHead _ (x:xs) = x

test :: [Nat] -> Nat
test xs = safeHead 0 xs  
```

To verify `test` LH _instantiates_ the  `a` of `safeHead` to `Nat`.

However, this sort of refinement instantiation is expensive and almost NEVER required in reflection-proofs.

The one exception is the use of the `?` operator where when we write

`e1 === e2 ? reason` 

we want to "instantiate" the type variable of `?` with the appropriate refinement in `reason`.

However, this kind of "instantiation" can be "recovered" with the abstract-refinement. So, we

1. Disable kvars/instantiation for type variables in `reflection` mode (or maybe in PLE mode?), but 
2. Preserve/restore it for the `?` by giving that operator a type signature that uses the abstract refinements.

Does that make sense?

**Comment by facundominguez** [comment]
Thanks Ranjit. That gives me clues about the implementation, but not a complete picture yet. If we have

```Haskell
reason :: { q }
reason = ...

f :: { p }
f = (e1 === e2) ? reason
```

The purpose of `?` is to introduce `reason :: { q }` among the hypothesis in the subtyping constraint

```
e1 : ...
e2 : ...
reason : { q }        -- Added by `?`
--------------------
{ e1 = e2 } <: { p }
```

The way in which either type variables or abstract refinements achieve that is still unclear (let's call this question 1). Maybe they produce

```
e1 : ...
e2 : ...
hpb : { pb }        -- Added by `?`
--------------------
{ pa } <: { p }


reason : { q }
--------------------
{ True } <: { pb }


e1 : ...
e2 : ...
reason : { e1 = e2 }
--------------------
{ True } <: { pa }
```

**Comment by facundominguez** [comment]
> However, this sort of refinement instantiation is expensive

How is this instantiation expensive? (call it question 2) Perhaps I also need a scheme of how the subtyping constraints look like in this case.

Still, there are many uses of `?` in tests which work without the abstract refinements with `--reflection` and `--ple`. In fact, it only seems to make a difference for `T1660`.

**Comment by ranjitjhala** [comment]
I think its like this:

```haskell
e :: { v: p1 && v == 12} 
e = ...

reason :: { p2 }
reason = ...

f :: {v: goal && v == 12 }
f = (e ? reason)
```

Where we want `(p1 && p2) => goal` but `p1` and `p2` do not individually imply `goal`.



**1. After ANF**

```
f = let { x1 = e ; x2 = reason } in (?) x1 x2
```

**2. After Instantiation** 

The `? :: pa -> pb -> pa` becomes `? :: $ka -> $kb -> $ka` and we get the following subtyping constraints

```
x1: p1, x2: p2 |- {v = x1} <: $ka          -- (1)
x1: p1, x2: p2 |- {v = x2} <: $kb         -- (2)
x1: p1, x2: p2 |- $ka(v) <: goal          -- (3)
```

**3. Constraint Solving**

The key bit is that (1) lets us "solve" `$ka` to 

```
$ka := \v -> exists x2. p2(x2) && p1(v)    
```

which "packs" `reason` into the refinement of `$ka` which then, lets us type the WHOLE expression `e ? reason` as

```
{v: exists x2. p2(x2) && p1(v) } 
```

essentially "combining" or "joining"  `reason` with the type of `e`. (I think...?) Does that help?

**Comment by facundominguez** [comment]
Thanks Ranjit. It does help, in that it conveys the intuition of how `?` is supposed to work. I feel I could put that in documentation, though I'd rather investigate first why the refinement type signature is optional for most tests.

**Comment by ranjitjhala** [comment]
Yes I am surprised ALL tests with ? don’t break so I  think my intuition
may be off too…

Re cost: I think in general we wanted to disable the “predicate
abstraction” / fixpoint computation in PLE proofs as it was unnecessary
(for the most part) and took up time — instantiating qualifiers trying out
candidates etc.



- Ranjit.

**Comment by facundominguez** [comment]
It turns out that `T1660.hs` enables `--fast`.

```
--fast --nopolyinfer

  No inference of polymorphic type application. Gives imprecision, but speedup.
```

This interferes with the refinement type inference of `e ? lemma`, which in such a case depends on the abstract predicates to show that `e ? lemma` evaluates to `e`.

The `pb` abstract predicate seems to be redundant in all cases. (!)

With or without the refinement type signature of `?`, ANF makes

```
e :: { v:Int | p1 && v == 12} 
e = ...

reason :: { p2 }
reason = ...

f :: {v:Int | goal && v == 12 }
f = let anf = reason
     in (e ? reason)
```
the anf binding is always in the subtyping constraint environment.

What stops verification is that `e ? reason` cannot be proven to have at least the same properties as `e` if the refinement type signature of `?` is missing and `--fast` is active.
