### ISSUE TITLE
Assumptions on local definitions are rejected

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#2419]
The following program was accepted until recently, but I broke it in #2418.

```
$ cat Test.hs
module Test where

{-@ f :: {v: Int | v > 0} @-}
f :: Int
f = g
  where
    {-@ assume g :: {v:Int | v > 0} @-}
    g :: Int
    g = 2

$ cabal exec ghc -- -fforce-recomp -fplugin=LiquidHaskell Test.hs
...
Test.hs:7:16: error: Unknown variable `g`
    Cannot resolve name
  |
7 |     {-@ assume g :: {v:Int | v > 0} @-}
  |                ^^
```

Fixing it should not be difficult. The new resolution logic in `LHNameResolution.hs` should look for `g` in `reLocalVars` before giving up, following the same logic as the old name resolution.

We need to add a regression test like this to the test suite, too.
