### ISSUE TITLE
LH inference is sensitive to literals

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#2237]
The following program fails
```haskell
{-# LANGUAGE MagicHash #-}
module Wrap0 () where
import Language.Haskell.Liquid.Prelude (liquidError, liquidAssertB)
import qualified GHC.Num.Integer
data Foo a = F a
{-@ flibInt :: (Num a, Ord a) => a -> Bool @-}
-- WORKS: flibInt x     = prop1 x (F (x + 1))
flibInt x     = prop1 x (F (x + fromInteger (GHC.Num.Integer.IS 1#)))
prop1 x (F y) = liquidAssertB (x < y)
```
with
```Haskell
../liquidhaskell/tests/pos/Wrap0.hs:13:31: error:
    Liquid Type Mismatch
    .
    The inferred type
      VV : {v : GHC.Types.Bool | (v <=> x < y)
                                 && v == (x < y)}
    .
    is not a subtype of the required type
      VV : {VV : GHC.Types.Bool | VV}
    .
    in the context
      x : a
       
      y : a
    Constraint id 17
   |
13 | prop1 x (F y) = liquidAssertB (x < y) 
```
However, it passes verification if the "WORKS" line is used instead.

ghc-9.4 desugars Haskell to the failing form, so I need to fix this to make progress with #2234.

**Comment by facundominguez** [comment]
Fixed by adding a spec to `GHC.Num.Integer.IS`. This one took me so long to discover! :see_no_evil:
